export const GET_PASSAGES = 'GET_PASSAGES';
export const LOADING_PASSAGES = "LOADING_PASSAGES";
export const SET_CURRENT_PASSAGE = "SET_CURRENT_PASSAGE";
export const REMOVE_PASSAGES = "REMOVE_PASSAGES";

export const GET_PROBLEMS = "GET_PROBLEMS";
export const REMOVE_PROBLEMS = "REMOVE_PROBLEMS"; 
export const LOADING_PROBLEMS = "LOADING_PROBLEMS";
export const SET_CURRENT_PROBLEM = "SET_CURRENT_PROBLEM"
