export const GET_PASSAGES = 'GET_PASSAGES';
export const LOADING_PASSAGES = "LOADING_PASSAGES";
export const SET_CURRENT_PASSAGE = "SET_CURRENT_PASSAGE";
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const RESET_CURRENT_PAGE = "RESET_CURRENT_PAGE";
export const REMOVE_PASSAGES = "REMOVE_PASSAGES"